temp_files/backup_photobyanni/about/urls.py
from django.urls import path
from . import views


app_name = "about"


urlpatterns = [
    path("", views.AboutView.as_view(), name="about_page"),
    path("contacts/", views.ContactsView.as_view(), name="contacts_page"),
    path("contacts/contact_with_me", views.ConnectWithMeView.as_view(), name="contact_with_me_page"),
]

temp_files/backup_photobyanni/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gallery.urls")),
    path("about/", include("about.urls")),
    path("api/", include("gallery.api.urls")),
    path("services/", include("services.urls")),
]


# для отображения картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

temp_files/backup_photobyanni/gallery/urls.py
from django.urls import path
from . import views


app_name = "gallery"


urlpatterns = [
    path("", views.AlbumsView.as_view(), name="gallery_page")
]

temp_files/backup_photobyanni/services/urls.py
from django.urls import path

from . import views


app_name = "services"


urlpatterns = [
    path("", views.index, name="temp_page"),
]

templates/include/footer.html
<div class="footer__dark-line"></div>
<div class="container footer__container">
    <ul class="footer__list">
        <li class="footer__list-item"><a class="footer__list-link" href="#">
        <!-- <object type="image/svg+xml" data="./images/icons/facebook.svg" class="footer__svg"></object> -->
            <svg class="footer__icon">
                <use href="./images/icons/sprite.svg#icon-facebook"></use>
            </svg>
            <p class="visually-hidden">facebook</p></a>
        </li>
        <li class="footer__list-item"><a class="footer__list-link" href="#">
            <svg class="footer__icon">
                <use href="./images/icons/sprite.svg#icon-twitter"></use>
            </svg>
            <p class="visually-hidden">tweeter</p></a>
        </li>
        <li class="footer__list-item"><a class="footer__list-link" href="#">
            <svg class="footer__icon">
                <use href="./images/icons/sprite.svg#icon-google-plus"></use>
            </svg>
            <p class="visually-hidden">google+</p></a>
        </li>
        <li class="footer__list-item"><a class="footer__list-link" href="#">
            <svg class="footer__icon">
                <use href="./images/icons/sprite.svg#icon-vimeo"></use>
            </svg>
            <p class="visually-hidden">vimeo</p></a>
        </li>
        <li class="footer__list-item"><a class="footer__list-link" href="#">
            <svg class="footer__icon">
                <use href="./images/icons/sprite.svg#icon-youtube"></use>
            </svg>
            <p class="visually-hidden">you-tube</p></a>
        </li>
        <li class="footer__list-item"><a class="footer__list-link" href="#">
            <svg class="footer__icon">
                <use href="./images/icons/sprite.svg#icon-pinterest"></use>
            </svg>
            <p class="visually-hidden">pinterest</p></a>
        </li>
    </ul>
    <p class="footer__descr">©  2020 . <a href="#">Looking for job</a></p>
</div>

templates/include/header.html
<div class= "bg-image"></div>
<header class="header container">
    <div class="header__container">
        <a href="{% url 'gallery:gallery_page' %}" class="logo link">
            PHOTO BY ANNI
            <span class="logo__descr link">LIFESTYLE ФОТОГРАФ</span>
        </a>
        <p class="header__description">Профессиональный фотограф <span>в стиле </span> lifestyle.</p>
    </div>
    {% include "include/sitebar.html" %}
</header>

templates/include/sitebar.html
<ul class="header__list">
    <li class="header__list-item">
        <div class="header__list-container">
            <a class="link header__list-link" href="{% url 'gallery:gallery_page' %}">Галерея</a>
            <a class="link header__list-link transparent" href="{% url 'gallery:gallery_page' %}">Галерея</a>
        </div>
    </li>
    <li class="header__list-item">
        <div class="header__list-container">
            <a class="link header__list-link" href="{% url 'services:temp_page' %}">Услуги</a>
            <a class="link header__list-link transparent" href="{% url 'services:temp_page' %}">Услуги</a>
        </div>
    </li>
    <li class="header__list-item">
        <div class="header__list-container">
            <a class="link header__list-link" href="{% url 'about:about_page' %}">О себе</a>
            <a class="link header__list-link transparent" href="{% url 'about:about_page' %}">О себе</a>
        </div>
    </li>
    <li class="header__list-item">
        <div class="header__list-container">
            <a class="link header__list-link" href="{% url 'about:contacts_page' %}">Контакты</a>
            <a class="link header__list-link transparent" href="{% url 'about:contacts_page' %}">Контакты</a>
        </div>
    </li>
</ul>