temp_files/backup_photobyanni/about/urls.py
from django.urls import path
from . import views


app_name = "about"


urlpatterns = [
    path("", views.AboutView.as_view(), name="about_page"),
    path("contacts/", views.ContactsView.as_view(), name="contacts_page"),
    path("contacts/contact_with_me", views.ConnectWithMeView.as_view(), name="contact_with_me_page"),
]

temp_files/backup_photobyanni/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gallery.urls")),
    path("about/", include("about.urls")),
    path("api/", include("gallery.api.urls")),
    path("services/", include("services.urls")),
]


# для отображения картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

temp_files/backup_photobyanni/about/models.py
from django.db import models
from django.core.files.uploadedfile import InMemoryUploadedFile

import sys
from io import BytesIO
from PIL import Image


class AboutMe(models.Model):
    profession = models.CharField(max_length=30, verbose_name="Професия")
    my_name = models.CharField(max_length=200, verbose_name="Фамилия Имя")
    about_me = models.TextField(verbose_name="Про меня")
    my_photo = models.ImageField(upload_to="about/", verbose_name="Мое фото")

    def __str__(self):
        return self.profession

    class Meta:
        verbose_name = "О себе"
        verbose_name_plural = "О себе"

    # сжатие фото пропорционально
    def save(self, *args, **kwargs):
        image = self.my_photo
        img = Image.open(image)
        new_img = img.convert("RGB")
        re_height = 600
        percent = round((re_height * 100) / img.height)
        re_width = round((img.width * percent) / 100)
        resize_new_img = new_img.resize((re_width, re_height),
                                        resample=Image.ANTIALIAS)
        filestream = BytesIO()  # преобразование изображения в поток данных (байты)
        resize_new_img.save(filestream, "JPEG", quality=90)  # сохранить изображение в filestream, формат, качество
        filestream.seek(0)
        name = ".".join(self.my_photo.name.split('.'))
        self.my_photo = InMemoryUploadedFile(
            filestream, "imageField", name, "jpeg/image", sys.getsizeof(filestream), None
        )
        super().save(*args, **kwargs)


class MyContacts(models.Model):
    title = models.CharField(verbose_name="Ресурс", max_length=50)
    value = models.CharField(verbose_name="Связь, ссылка", max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Мой контакт"
        verbose_name_plural = "Мои контакты"


class ContactWithMe(models.Model):
    name = models.CharField(verbose_name="Фамилия Имя", max_length=255)
    email = models.CharField(verbose_name="Электронная почта", max_length=255)
    phone = models.CharField(verbose_name="Номер телефона", max_length=255)
    theme = models.CharField(verbose_name="Тема обращения", max_length=255)
    text = models.TextField(verbose_name="Текст сообщения")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Сообщение фотографу"
        verbose_name_plural = "Сообщения фотографу"

temp_files/backup_photobyanni/about/forms.py
from django import forms

from .models import ContactWithMe


class ContactWithMeForm(forms.ModelForm):
    class Meta:
        model = ContactWithMe
        fields = [
            "name",
            "email",
            "phone",
            "theme",
            "text"
        ]
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "services__form-input",
                "placeholder": "Фамилию и Имя",
                "minlength": "2"
            }),
            "email": forms.TextInput(attrs={
                "class": "services__form-input",
                "placeholder": "Электронную почту"
            }),
            "phone": forms.TextInput(attrs={
                "class": "services__form-input",
                "placeholder": "Номер телефона"
            }),
            "theme": forms.TextInput(attrs={
                "class": "services__form-input",
                "placeholder": "Тема обращения"
            }),
            "text": forms.Textarea(attrs={
                "class": "services__form-textarea",
                "placeholder": "Сообщение",
                "cols": "30",
                "rows": "10",
                "minlength": "10",

            }),
        }

temp_files/backup_photobyanni/about/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.http import HttpResponseRedirect

from .models import AboutMe, MyContacts
from .forms import ContactWithMeForm


class AboutView(View):
    def get(self, request, *args, **kwargs):
        about_me = AboutMe.objects.first()
        return render(request, "about/about.html", {"about_me": about_me})


class ContactsView(View):
    def get(self, request, *args, **kwargs):
        contacts = MyContacts.objects.all()
        return render(request, "about/contacts.html", {"contacts": contacts})


class ConnectWithMeView(View):
    def get(self, request, *args, **kwargs):
        form = ContactWithMeForm(request.POST or None)
        context = {
            "form": form,
        }
        return render(request, "about/form_to_connect.html", context)

    def post(self, request, *args, **kwargs):
        form = ContactWithMeForm(request.POST or None)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.name = form.cleaned_data["name"]
            new_message.email = form.cleaned_data["email"]
            new_message.phone = form.cleaned_data["phone"]
            new_message.text = form.cleaned_data["text"]
            new_message.save()
            return HttpResponseRedirect("/")
        context = {
            "form": form,
        }
        return render(request, "about/form_to_connect.html", context)



temp_files/backup_photobyanni/templates/about/about.html
<!--Подключение шаблона и static-->
{% extends "about/about_base.html" %}
{% load static %}


<!--Заголовок этой страницы-->
{% block title %}О себе{% endblock title %}


<!--Подключение стилей для этой страницы-->
{% block styles %}
<link rel="stylesheet" href="{% static 'about/css/about.css' %}">
{% endblock styles %}


<!--Блок main-->
{% block content_about %}
{% if about_me %}
<img class="about__pic" src="{{ about_me.my_photo.url }}" alt="My photo">
<div class="about__descr-section">
    <h2 class="about__descr">{{ about_me.profession }}</h2>
    <h3>{{ about_me.my_name }}</h3>
    <p class="about__descr-about_me">{{ about_me.about_me|linebreaks }}</p>
<!--    <button class="about__more" type="button">more<span> ></span> </button>-->
</div>
{% else %}
    <h1 class="services__title">Данных нет</h1>
{% endif %}
{% endblock content_about %}

temp_files/backup_photobyanni/templates/about/about_base.html
<!--Подключение шаблона и static-->
{% extends "base/base.html" %}

<!--Блок main-->
{% block main %}
<div class="container about">
    <button class="about__close-btn" type="button">X</button>
    <div class="about__inner-container">

        {% block content_about %}
        {% endblock content_about %}

    </div>
</div>
{% endblock main %}

temp_files/backup_photobyanni/templates/about/contacts.html
<!--Подключение шаблона и static-->
{% extends "about/about_base.html" %}
{% load static %}


<!--Заголовок этой страницы-->
{% block title %}Контакты{% endblock title %}


<!--Подключение стилей для этой страницы-->
{% block styles %}
<link rel="stylesheet" href="{% static 'about/css/contacts.css' %}">
{% endblock styles %}


<!--Блок main-->
{% block content_about %}
<div class="services__wrapper">
    <h2 class="services__title">Контактная информация</h2>
    {% if contacts %}
        {% for contact in contacts %}
            <div>
                <p class="services__description">{{ contact.title }} :</p>
            {% if "http" in contact.value %}
                    <a href="{{ contact.value }}" class="services__description-link">нажимай</a>
            {% else %}
                    <p class="services__description-link">{{ contact.value }}</p>
            {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <h1 class="services__title">Данных нет</h1>
    {% endif %}
    <a href="{% url 'about:contact_with_me_page' %}" class="services__description-link-to-form">
        <p>или заполните форму, чтобы связаться со мной</p>
    </a>
</div>
{% endblock content_about %}

temp_files/backup_photobyanni/templates/about/form_to_connect.html
<!--Подключение шаблона и static-->
{% extends "about/about_base.html" %}
<!--{% load static %}-->


<!--Заголовок этой страницы-->
{% block title %}Обратится к фотографу{% endblock title %}


<!--Подключение стилей для этой страницы-->
{% block styles %}
<link rel="stylesheet" href="{% static 'about/css/contacts.css' %}">
{% endblock styles %}


{% block content_about %}
<form class="services__form" action="#" method="POST">
    {% csrf_token %}
    {{ form.name }}
    {{ form.email }}
    {{ form.phone }}
    {{ form.theme }}
    {{ form.text }}

    <div class="form__btn-wrapper">
        <button class="form__btn" type="submit">Send message</button>
        <p class="form__description"></p>
    </div>
</form>
{% endblock content_about %}